# Generated by Django 4.2.5 on 2023-12-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=1000)),
                ('slug', models.SlugField()),
                ('owner', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('prix', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to='uploads/')),
                ('categorie', models.CharField(max_length=1000)),
                ('promotion', models.BooleanField(default=False)),
                ('debut_promo', models.DateField(blank=True, null=True)),
                ('fin_promo', models.DateField(blank=True, null=True)),
                ('pourcentage_promo', models.FloatField()),
                ('content', models.TextField()),
            ],
        ),
    ]
