# Generated by Django 4.2.5 on 2023-12-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
