# Generated by Django 4.2.5 on 2023-12-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admuser', '0005_alter_articles_pourcentage_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
