# Generated by Django 4.2.5 on 2023-12-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admuser', '0007_alter_articles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='prix_final',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
