# Generated by Django 4.2.5 on 2023-12-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admuser', '0008_articles_prix_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='prix_final',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
